name: why_not_143_team
description: A new Flutter project.

publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  google_fonts: ^2.3.2
  flutter_screenutil: ^5.4.0+1
  introduction_screen: ^3.0.2
  firebase_core: ^1.16.0
  firebase_auth: ^3.3.17
  cloud_firestore: ^3.1.14
  google_sign_in: ^5.3.1
  provider: ^6.0.2
  lottie: ^1.3.0
  fluttertoast: ^8.0.9
  flutter_inappwebview: ^5.4.3+4
  flutter_zoom_drawer: ^3.0.1
  url_launcher: ^6.1.0
  stacked: ^2.3.6
  stacked_hooks: ^0.2.2
  flutter_launcher_icons: ^0.9.2
  dio: ^4.0.6

flutter_icons:
  android: "launcher_icon"
  image_path: "assets/images/patidost.png"
  



dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:

  uses-material-design: true

  assets:
      - assets/images/
     
  fonts:

    - family: Pacifico
      fonts:
        - asset: assets/google_fonts/Pacifico-Regular.ttf
  